spring:
  application:
    name: user-api

server:
  port: 8082 # Port for user-api service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true