server:
  port: ${PORT:8080}

eureka:
    instance:
      hostname: ${GATEWAY_API_HOST:ec2-51-21-135-63.eu-north-1.compute.amazonaws.com}
    client:
      serviceUrl:
        defaultZone: http://${EUREKA_HOST:ec2-51-21-135-63.eu-north-1.compute.amazonaws.com}:8761/eureka/

api-urls:
  user-api: https://user-api-ml66.onrender.com/actuator/health
  recipe-api: https://recipe-api-yikp.onrender.com/actuator/health
  auth-api: https://auth-api-i2v8.onrender.com/actuator/health

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://main.d35zjw8awdp41d.amplifyapp.com/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true