server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: lb://auth-api
          predicates:
            - Path=/auth-api/**

        - id: recipe-api
          uri: lb://recipe-api
          predicates:
            - Path=/recipes-api/**

        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/users-api/**

        - id: admin-api
          uri: lb://admin-api
          predicates:
            - Path=/admin-api/**

        - id: interaction-api
          uri: lb://interaction-api
          predicates:
            - Path=/interaction-api/**

        - id: notification-api
          uri: lb://notification-api
          predicates:
            - Path=/notification-api/**