spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: recipe-api
          uri: lb://recipe-api
          predicates:
            - Path=/api/recipes/**

server:
  port: 8080 # Port for api-gateway service

