spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: lb://auth-api
          predicates:
            - Path=/auth-api/**

        - id: recipe-api
          uri: lb://recipe-api
          predicates:
            - Path=/recipe-api/**, /fridge-api/**

        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/user-api/**

        - id: admin-api
          uri: lb://admin-api
          predicates:
            - Path=/admin-api/**

        - id: interaction-api
          uri: lb://interaction-api
          predicates:
            - Path=/interaction-api/**

        - id: notification-api
          uri: lb://notification-api
          predicates:
            - Path=/notification-api/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
