spring:
  application:
    name: auth-api

server:
  port: 8083 # Port for auth-api service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true