server:
  port: ${PORT:443} # Port for auth-api service

eureka:
  instance:
    hostname: ${AUTH_API_HOST:auth-api-863962813656.europe-north1.run.app}
    secure-port-enabled: true
    non-secure-port-enabled: false
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:ec2-51-21-135-63.eu-north-1.compute.amazonaws.com}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info