server:
  port: ${PORT:8083} # Port for auth-api service

eureka:
  client:
    serviceUrl:
      defaultZone: https://api-eureka-863962813656.europe-central2.run.app:8761/eureka
    fetchRegistry: true
    registerWithEureka: true