spring:
  application:
    name: recipe-api

server:
  port: 8081 # Port for recipe-api service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true