spring:
  application:
    name: recipe-api
  profiles:
    active: dev

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info