name: Docker Push

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.changed-services.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed projects
        id: changed-services
        run: |
          # Check for changes in the specific directories
          CHANGED_SERVICES=""
          if git diff --name-only HEAD^ HEAD | grep -q "^auth-api/"; then
            CHANGED_SERVICES="${CHANGED_SERVICES} auth-api"
          fi
          if git diff --name-only HEAD^ HEAD | grep -q "^user-api/"; then
            CHANGED_SERVICES="${CHANGED_SERVICES} user-api"
          fi
          if git diff --name-only HEAD^ HEAD | grep -q "^recipe-api/"; then
            CHANGED_SERVICES="${CHANGED_SERVICES} recipe-api"
          fi

          echo "services=${CHANGED_SERVICES}" >> $GITHUB_OUTPUT

  docker:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR files
        uses: actions/download-artifact@v3
        with:
          name: jar-files

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          for SERVICE in ${{ needs.detect-changes.outputs.changed-services }}; do
            echo "Building and pushing Docker image for $SERVICE"
            docker build -t develoburs/$SERVICE:latest --platform=linux/amd64 -f $SERVICE/Dockerfile .
            docker push develoburs/$SERVICE:latest
          done
