name: Push Docker Image

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR files
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: gradle-build-without-test.yml
          name: jar-files

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for auth-api
        run: |
          echo "Building and pushing Docker image for auth-api"
          docker build -t develoburs/auth-api:latest -f auth-api/Dockerfile .
          docker push develoburs/auth-api:latest

      - name: Build and push Docker image for user-api
        run: |
          echo "Building and pushing Docker image for user-api"
          docker build -t develoburs/user-api:latest -f user-api/Dockerfile .
          docker push develoburs/user-api:latest

      - name: Build and push Docker image for recipe-api
        run: |
          echo "Building and pushing Docker image for recipe-api"
          docker build -t develoburs/recipe-api:latest -f recipe-api/Dockerfile .
          docker push develoburs/recipe-api:latest