name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle with caching for dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Build and publish shared library to Maven local
      - name: Publish shared library to Maven local
        run: cd shared && ./gradlew publishToMavenLocal

      # Cache Maven local repository to avoid re-publishing the shared library
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-local-${{ hashFiles('shared/**/*.java') }}
          restore-keys: |
            maven-local-

      # Build the entire project
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generate and submit dependency graph for Dependabot Alerts
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
